version: '3'
services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - $DEV_DIR/devops/nginx/conf/:/etc/nginx/conf.d/
            - $DEV_DIR/devops/nginx/log/:/var/log/nginx/
        command: nginx -g 'daemon off;'
        links:
            - php:php
        restart: always
    php:
        container_name: php
        build: ./php
        image: php:custom
        ports:
            - "9000:9000"
            - "9090:9090"
        volumes:
            - $DEV_DIR/devops/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
            - $DEV_DIR/devops/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - $DEV_DIR/:/var/html/
        links:
            - mysql:mysql
        restart: always
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - $DEV_DIR/devops/mysql/data/:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
